name: Native Tests

on:
  workflow_call:
    secrets:
      webhook:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build & Test - Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [ 8, 17 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build Cryptobox
        run: |
          make cryptobox

      - name: Build Native Bindings
        run: |
          make compile-native

      - name: Compile Cryptobox4j & Run Tests
        run: |
          make verify-java

      - name: Webhook to Wire
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Cryptobox4J - Test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.webhook }}
        if: failure()
